# Generated by Django 3.2.6 on 2021-08-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_inventory_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='summoner_level',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='summoner_name',
        ),
    ]
