# Generated by Django 3.2.6 on 2021-08-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210814_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='voters',
            field=models.CharField(default='string', max_length=100),
            preserve_default=False,
        ),
    ]
