# Generated by Django 3.2.6 on 2021-08-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inventory_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='voters',
            new_name='voter',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.AddField(
            model_name='inventory',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
